# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

# username: bshomemade
# password: password

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  # host: 127.0.0.1
  database: bshomemade_dev	
  username: bshomemade
  password: 

  test:
  adapter: postgresql
  # host: 127.0.0.1
  database: bshomemade_test
  username: bshomemade
  password: 	



# production:
#   <<: *default
#   database: db/production.sqlite3


