# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bshomemade_dev	
  username: <%= ENV.fetch('DB_USER_NAME', nil) %>
  password: <%= ENV.fetch('DB_PASSWORD', nil) %>

test:
  <<: *default
  database: bshomemade_test
  username: <%= ENV.fetch('DB_USER_NAME', nil) %>
  password: <%= ENV.fetch('DB_PASSWORD', nil) %>

# production:
#   <<: *default
#   database: db/production.sqlite3
